[[main]]
  name = "CV"
  url = "/cv"
  weight = 1

[[main]]
  name = "Research"
  url = "/research"
  weight = 2

[[main]]
  name = "Outreach"
  url = "/outreach"
  weight = 3

[[main]]
  name = "SoftReminder"
  url = "/softreminder"
  weight = 4

[[main]]
  name = "Writing"
  url = "/writing"
  weight = 5
